modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/QWERTY770/MCBBS-Wiki-Mod/issues"
[[mods]]
modId="mcbbswiki"
version="0.5b2"
displayName="MCBBS Wiki"
displayURL="https://github.com/QWERTY770/MCBBS-Wiki-Mod"
logoFile="mcbbswiki.png"
credits="QWERTY_52_38"
authors="QWERTY_52_38"
description='''

'''
[[dependencies.mcbbswiki]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcbbswiki]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.16.4]"
    ordering="NONE"
    side="BOTH"