modLoader="javafml"
loaderVersion="[33,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/QWERTY770/MCBBS-Wiki-Mod/issues"
[[mods]]
modId="mcbbswiki"
version="0.8b1"
displayName="MCBBS Wiki"
displayURL="https://github.com/QWERTY770/MCBBS-Wiki-Mod"
logoFile="mcbbswiki.png"
credits="QWERTY_52_38"
authors="QWERTY_52_38"
description='''https://www.mcmod.cn/class/3343.html
'''
[[dependencies.mcbbswiki]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcbbswiki]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1, 1.16.5]"
    ordering="NONE"
    side="BOTH"