modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/QWERTY770/MCBBS-Wiki-Mod/issues"
[[mods]]
modId="mcbbswiki"
version="0.8b2"
displayName="MCBBS Wiki"
displayURL="https://github.com/QWERTY770/MCBBS-Wiki-Mod"
logoFile="mcbbswiki.png"
credits="QWERTY_52_38"
authors="QWERTY_52_38"
description='''https://www.mcmod.cn/class/3343.html
'''
[[dependencies.mcbbswiki]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcbbswiki]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17, 1.17.1]"
    ordering="NONE"
    side="BOTH"